version: '3'

services:
  producer:
    build:
      context: ./producer
      dockerfile: Dockerfile
    command: npm start
    volumes:
      - ./producer:/usr/src/app
    networks:
      - app-network
    environment:
      - MESSAGE_QUEUE=amqp://rabbitmq
    links:
      - rabbitmq
    depends_on:
      - rabbitmq

  consumer:
    build:
      context: ./consumer
      dockerfile: Dockerfile
    command: npm start
    volumes:
      - ./consumer:/usr/src/app
    networks:
      - app-network
    environment:
      - MESSAGE_QUEUE=amqp://rabbitmq
    links:
      - rabbitmq
    depends_on: 
      - rabbitmq

  rabbitmq:
    image: rabbitmq:3.7.4
    networks:
      - app-network
    ports: 
      - "5672:5672"

networks:
  app-network:
    driver: bridge
