version: '3'

services:
  producer:
    build:
      context: ./producer
      dockerfile: Dockerfile
    command: npm start
    volumes:
      - ./producer:/usr/src/app
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
